import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'
import { useEffect } from 'react'

export default function Home() {

  let [todo, setTodo] = useState([]);

  const getTodoDetails = () => {
    axios.get(
      'http://127.0.0.1:8000/api/'
    )
      .then((res) => {
        setTodo({ todo: res.data });
      })
      .catch((err) => {
        console.log(err);
      }
      )
  }

  // const getTodoDetails = async () => {
  //   const res = await axios({
  //     method: 'get',
  //     url: 'http://127.0.0.1:8000/api/',
  //     headers: {
  //       'Content-Type': 'application/json;charset=UTF-8',
  //       'Access-Control-Allow-Origin': '*',
  //     },

  //   });

  //   setTodo(res.data);
  // };


  useEffect(() => {

    // prevent it from reading allow it to load REST API, just in case
    setTimeout(() => {
      getTodoDetails();
    }, 100);

  }, [todo]);



  console.log(todo.todo);
  console.log(typeof todo.todo);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Todo List</h1>
      <div>
        {
          // conditional rendering
          todo && (todo.todo || []).map((item) => {
            return (
              <div key={item.id}>
                <h1>{item.title}</h1>
                <p>{item.body}</p>
              </div>
            )
          })
        }
      </div>
    </div>
  )
}
